/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/24/2016
 */
package com.uber.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TimeEstimateCollection 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4706983474537511913L;
    private List<TimeEstimate> times;
    /** GETTER
     * List of time estimates
     */
    @JsonGetter("times")
    public List<TimeEstimate> getTimes ( ) { 
        return this.times;
    }
    
    /** SETTER
     * List of time estimates
     */
    @JsonSetter("times")
    public void setTimes (List<TimeEstimate> value) { 
        this.times = value;
        notifyObservers(this.times);
    }
 
}
 